[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
]

viaIr = true
optimizer = true
optimizer_runs = 200

evm_version = "prague"

# Enable FFI for JavaScript script integration
ffi = true

# Increase gas limit for tests
gas_limit = 100_000_000
block_gas_limit = 100_000_000

[profile.test]
gas_limit = 100_000_000
block_gas_limit = 100_000_000

# For specific heavy tests
[profile.heavy]
gas_limit = 1_000_000_000
block_gas_limit = 1_000_000_000